---
- hosts: localhost
  connection: local
  become: true

  tasks:

  - name: Install Archlinux Packages
    ansible.builtin.package:
      name: 
        - kitty
        - otf-fira-mono
        - vim
        - bash-completion
        - tmux
        - fastfetch
        - gnome-boxes
        - cronie
        - bpytop
        - sway
        - waybar
        - swayidle
        - swaylock
        - brightnessctl
        - playerctl
        - blueman
        - dmenu
        - xorg-xwayland
        - firefox
        - ttf-font-awesome
        - polkit-gnome
        - xorg-xhost
        - gvfs
        - gst-libav
        - eog
        - grim
        - totem
      state: present
    when: ansible_distribution == "Archlinux"

  - name: Remove Archlinux Packages
    ansible.builtin.package:
      name:
        - gnome-backgrounds
        - gnome-books
        - gnome-calculator
        - gnome-clocks
        - gnome-contacts
        - gnome-font-viewer
        - gnome-characters
        - gnome-maps
        - gnome-software-packagekit-plugin
        - gnome-software
        - gnome-system-monitor
        - gnome-terminal
        - gnome-user-docs
        - gnome-epub-thumbnailer
        - epiphany
      state: absent
    when: ansible_distribution == "Archlinux"

  - name: Install Fedora Workstation Packages
    dnf:
      name: 
        - kitty
        - vim
        - bash-completion
        - tmux
        - fastfetch
        - gnome-tweaks
        - cronie
        - bpytop
      state: present
    when: ansible_pkg_mgr == "dnf"

  - name: Delete Fedora Workstation Packages
    dnf:
      name: 
        - epiphany
      state: absent
    when: ansible_pkg_mgr == "dnf"

  - name: Install openSUSE Packages
    zypper:
      name: 
        - kitty
        - vim
        - bash-completion
        - tmux
        - neofetch
        - gnome-tweaks
        - cronie
        - bpytop
      state: present
    when: ansible_distribution == "openSUSE"

  - name: Delete openSUSE Packages
    zypper:
      name: 
        - epiphany
      state: absent
    when: ansible_distribution == "openSUSE"

  - name: Set .bashrc file
    copy:
      src: files/.bashrc
      dest: /home/cyfraka/.bashrc
      owner: cyfraka
      group: cyfraka

  - name: Set .bash_profile file
    copy:
      src: files/.bash_profile
      dest: /home/cyfraka/.bash_profile
      owner: cyfraka
      group: cyfraka

  - name: set .vimrc file
    copy:
      src: files/.vimrc
      dest: /home/cyfraka/.vimrc
      owner: cyfraka
      group: cyfraka

  - name: set .tmux.conf file
    copy:
      src: files/.tmux.conf
      dest: /home/cyfraka/.tmux.conf
      owner: cyfraka
      group: cyfraka

  - name: set .gitconfig file
    copy:
      src: files/.gitconfig
      dest: /home/cyfraka/.gitconfig
      owner: cyfraka
      group: cyfraka

  - name: Create .config directory
    file:
      path: /home/cyfraka/.config
      state: directory
      owner: cyfraka
      group: cyfraka

  - name: Create Kitty directory
    file:
      path: /home/cyfraka/.config/kitty
      state: directory
      owner: cyfraka
      group: cyfraka

  - name: Set Kitty .conf file
    copy:
      src: files/.config/kitty/kitty.conf
      dest: /home/cyfraka/.config/kitty/kitty.conf
      owner: cyfraka
      group: cyfraka

  - name: Create Sway directory
    file:
      path: /home/cyfraka/.config/sway
      state: directory
      owner: cyfraka
      group: cyfraka

  - name: Set Sway .conf file
    copy:
      src: files/.config/sway/config
      dest: /home/cyfraka/.config/sway/config
      owner: cyfraka
      group: cyfraka

  - name: Create Waybar directory
    file:
      path: /home/cyfraka/.config/waybar
      state: directory
      owner: cyfraka
      group: cyfraka

  - name: Set Waybar .conf file
    copy:
      src: files/.config/waybar/config
      dest: /home/cyfraka/.config/waybar/config
      owner: cyfraka
      group: cyfraka

  - name: Set Waybar .css file
    copy:
      src: files/.config/waybar/style.css
      dest: /home/cyfraka/.config/waybar/style.css
      owner: cyfraka
      group: cyfraka

  - name: Create Pictures directory
    file:
      path: /home/cyfraka/Pictures
      state: directory
      owner: cyfraka
      group: cyfraka

  - name: Create Wallpapers directory
    file:
      path: /home/cyfraka/Pictures/Wallpapers
      state: directory
      owner: cyfraka
      group: cyfraka

  - name: Copy picture Cyfraka
    copy:
      src: files/Cyfraka.jpg
      dest: /home/cyfraka/Pictures/Wallpapers/Cyfraka.jpg
      owner: cyfraka
      group: cyfraka

  - name: Copy picture 80s
    copy:
      src: files/80s.jpg
      dest: /home/cyfraka/Pictures/Wallpapers/80s.jpg
      owner: cyfraka
      group: cyfraka

  - name: Set wallpaper
    become_user: cyfraka
    dconf:
      key: "/org/gnome/desktop/background/picture-uri"
      value: "'file:///home/cyfraka/Pictures/Wallpapers/80s.jpg'"

  - name: Set clock show date
    become_user: cyfraka
    dconf:
      key: "/org/gnome/desktop/interface/clock-show-weekday"
      key: "/org/gnome/desktop/interface/clock-show-seconds"
      value: "true"

  - name: Set inactive timeout
    become_user: cyfraka
    dconf:
      key: "/org/gnome/settings-daemon/plugins/power/sleep-inactive-ac-type"
      value: "'nothing'"

  - name: Show battery percentage
    become_user: cyfraka
    dconf:
      key: "/org/gnome/desktop/interface/show-battery-percentage"
      value: "true"

  - name: gnome | keybindings | set custom-keybindings
    tags: gnome,keybindings
    become_user: cyfraka
    dconf:
      key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings"
      value: "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/']"

  - name: gnome | keybindings | set Kitty keybinding
    tags: gnome,keybindings
    become_user: cyfraka
    dconf:
      key: "{{ item.key }}"
      value: "{{ item.value}}"
    with_items:
      - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/name", value: "'Kitty'" }
      - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/binding", value: "'<Super>a'" }
      - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/command", value: "'kitty'" }

  - name: gnome | keybindings | set Firefox keybinding
    tags: gnome,keybindings
    become_user: cyfraka
    dconf:
      key: "{{ item.key }}"
      value: "{{ item.value}}"
    with_items:
      - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/name", value: "'Firefox'" }
      - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/binding", value: "'<Super>w'" }
      - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/command", value: "'firefox'" }

  - name: gnome | keybindings | set Nautilus keybinding
    tags: gnome,keybindings
    become_user: cyfraka
    dconf:
      key: "{{ item.key }}"
      value: "{{ item.value}}"
    with_items:
      - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/name", value: "'Nautilus'" }
      - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/binding", value: "'<Super>z'" }
      - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/command", value: "'nautilus'" }

  - name: gnome | keybindings | set Workspace 1
    tags: gnome,keybindings
    become_user: cyfraka
    dconf:
      key: "/org/gnome/desktop/wm/keybindings/{{ item.key }}"
      value: "{{ item.value}}"
    with_items:
     - { key: switch-to-workspace-1, value: "['<Super>1']" }

  - name: gnome | keybindings | set Workspace 2
    tags: gnome,keybindings
    become_user: cyfraka
    dconf:
      key: "/org/gnome/desktop/wm/keybindings/{{ item.key }}"
      value: "{{ item.value}}"
    with_items:
     - { key: switch-to-workspace-2, value: "['<Super>2']" }

  - name: gnome | keybindings | set Workspace 3
    tags: gnome,keybindings
    become_user: cyfraka
    dconf:
      key: "/org/gnome/desktop/wm/keybindings/{{ item.key }}"
      value: "{{ item.value}}"
    with_items:
     - { key: switch-to-workspace-3, value: "['<Super>3']" }

  - name: gnome | keybindings | set Workspace 4
    tags: gnome,keybindings
    become_user: cyfraka
    dconf:
      key: "/org/gnome/desktop/wm/keybindings/{{ item.key }}"
      value: "{{ item.value}}"
    with_items:
     - { key: switch-to-workspace-4, value: "['<Super>4']" }

  - name: gnome | keybindings | move to Workspace 1
    tags: gnome,keybindings
    become_user: cyfraka
    dconf:
      key: "/org/gnome/desktop/wm/keybindings/{{ item.key }}"
      value: "{{ item.value}}"
    with_items:
     - { key: move-to-workspace-1, value: "['<Shift><Super>exclam']" }

  - name: gnome | keybindings | move to Workspace 2
    tags: gnome,keybindings
    become_user: cyfraka
    dconf:
      key: "/org/gnome/desktop/wm/keybindings/{{ item.key }}"
      value: "{{ item.value}}"
    with_items:
     - { key: move-to-workspace-2, value: "['<Shift><Super>at']" }

  - name: gnome | keybindings | move to Workspace 3
    tags: gnome,keybindings
    become_user: cyfraka
    dconf:
      key: "/org/gnome/desktop/wm/keybindings/{{ item.key }}"
      value: "{{ item.value}}"
    with_items:
     - { key: move-to-workspace-3, value: "['<Shift><Super>numbersign']" }

  - name: gnome | keybindings | move to Workspace 4
    tags: gnome,keybindings
    become_user: cyfraka
    dconf:
      key: "/org/gnome/desktop/wm/keybindings/{{ item.key }}"
      value: "{{ item.value}}"
    with_items:
     - { key: move-to-workspace-4, value: "['<Shift><Super>dollar']" }


  - name: gnome | keybindings | set Close
    tags: gnome,keybindings
    become_user: cyfraka
    dconf:
      key: "/org/gnome/desktop/wm/keybindings/{{ item.key }}"
      value: "{{ item.value}}"
    with_items:
     - { key: close, value: "['<Super>q']" }

  - name: gnome | keybindings | set Fullscreen
    tags: gnome,keybindings
    become_user: cyfraka
    dconf:
      key: "/org/gnome/desktop/wm/keybindings/{{ item.key }}"
      value: "{{ item.value}}"
    with_items:
      - { key: toggle-fullscreen, value: "['<super>f']" }

  - name: gnome | appearance | set GTK theme
    become_user: cyfraka
    dconf:
      key: "/org/gnome/desktop/interface/gtk-theme"
      value: "'Adwaita-dark'"

  - name: Add Ansible User
    user:
      name: angel
      system: yes

  - name: Set sudo for Ansible User
    copy:
      src: files/sudoer_angel
      dest: /etc/sudoers.d/angel
      owner: root
      group: root
      mode: 0440

  - name: Add Ansible-Pull Cron Job
    cron:
      name: ansible auto-provision
      user: angel
      minute: "*/10"
      job: ansible-pull -o -U https://github.com/Cyfraka/ansible-ThinkPad.git

